package http

import (
	"bufio"
	"os"
	"regexp"
	"testing"
)

// secretAuditGolden is the loader's committed classification of every settings
// field in the vendored corpus. It is regenerated by the loader's own
// TestSecretClassifierCorpusAudit whenever `make vendor-defs` changes the
// snapshot, which is exactly when the two vocabularies can drift apart.
const secretAuditGolden = "../indexer/cardigann/loader/testdata/secret_audit.txt"

var secretAuditLine = regexp.MustCompile(`name=(\S+)\s+secret=true`)

// TestRedactionCoversEverySecretClassifiedField ties together the two
// independent answers this codebase has to "is this field a credential":
//
//	loader.SettingsField.IsSecret()  decides what is ENCRYPTED AT REST
//	secretNameRe (this package)      decides what is REDACTED IN LOGS
//
// Nothing else forces them to agree. A field can therefore be stored encrypted
// and still be printed in the clear — which is how `pin` (8 vendored
// definitions) sat outside the alternation while `pid` was inside it.
//
// The check is a table over a golden that already exists, so it costs
// microseconds and fails the moment a re-vendor introduces a secret-shaped
// field name the redactor does not recognise.
func TestRedactionCoversEverySecretClassifiedField(t *testing.T) {
	t.Parallel()

	f, err := os.Open(secretAuditGolden)
	if err != nil {
		t.Fatalf("open secret audit golden: %v", err)
	}
	defer f.Close()

	seen := map[string]bool{}
	scan := bufio.NewScanner(f)
	for scan.Scan() {
		m := secretAuditLine.FindStringSubmatch(scan.Text())
		if m == nil {
			continue
		}
		seen[m[1]] = true
	}
	if err := scan.Err(); err != nil {
		t.Fatalf("read secret audit golden: %v", err)
	}
	if len(seen) == 0 {
		t.Fatal("no secret=true fields found in the audit golden; the parser or the golden's format changed")
	}

	for name := range seen {
		if !isSecretParam(name) {
			t.Errorf("field %q is classified secret=true (encrypted at rest) but does NOT match the redaction vocabulary — its value would be logged in the clear; add it to secretNameAlternation", name)
		}
	}
}
