import createClient, { type Client } from "openapi-fetch"
import { getBaseUrl } from "@/lib/base-url"
import type { components, operations, paths } from "@/types/api.gen"

// Convenience aliases onto the generated schema (web/src/types/api.gen.ts, committed,
// regenerated by `bun run generate:api` from internal/web/swagger/openapi.yaml). These are
// derived references into the generated types, not hand-mirrored copies — never add a
// type here whose shape is retyped by hand instead of indexed from `components`/
// `operations`.
export type Instance = components["schemas"]["Instance"]
export type Setting = components["schemas"]["Setting"]
export type InstanceDetail = components["schemas"]["InstanceDetail"]
export type DefinitionSummary = components["schemas"]["DefinitionSummary"]
// A definitions-list row: a summary, plus the failure fields set on a definition
// that could not be loaded (see /api/definitions).
export type DefinitionEntry = components["schemas"]["DefinitionEntry"]
export type SettingField = components["schemas"]["SettingField"]
export type DefinitionDetail = components["schemas"]["DefinitionDetail"]
export type AddIndexer = components["schemas"]["AddIndexer"]
export type UpdateIndexer = components["schemas"]["UpdateIndexer"]
export type Capabilities = components["schemas"]["Capabilities"]
export type SearchResults = components["schemas"]["SearchResults"]
export type AggregateSearchResults = components["schemas"]["AggregateSearchResults"]
export type SearchMember = components["schemas"]["SearchMember"]
export type Release = components["schemas"]["Release"]
export type TestResult = components["schemas"]["TestResult"]
export type App = components["schemas"]["App"]
export type UpdateApp = components["schemas"]["UpdateApp"]
export type QuiInstance = components["schemas"]["QuiInstance"]
export type QuiInstances = components["schemas"]["QuiInstances"]
export type AppConnection = components["schemas"]["AppConnection"]
export type CreateConnection = components["schemas"]["CreateConnection"]
export type UpdateConnection = components["schemas"]["UpdateConnection"]
export type AnnounceConnection = components["schemas"]["AnnounceConnection"]
export type CreateAnnounceConnection = components["schemas"]["CreateAnnounceConnection"]
export type UpdateAnnounceConnection = components["schemas"]["UpdateAnnounceConnection"]
export type Notification = components["schemas"]["Notification"]
export type CreateNotification = components["schemas"]["CreateNotification"]
export type UpdateNotification = components["schemas"]["UpdateNotification"]
export type Proxy = components["schemas"]["Proxy"]
export type CreateProxy = components["schemas"]["CreateProxy"]
export type UpdateProxy = components["schemas"]["UpdateProxy"]
export type Solver = components["schemas"]["Solver"]
export type CreateSolver = components["schemas"]["CreateSolver"]
export type UpdateSolver = components["schemas"]["UpdateSolver"]
export type DownloadClient = components["schemas"]["DownloadClient"]
export type CreateDownloadClient = components["schemas"]["CreateDownloadClient"]
export type UpdateDownloadClient = components["schemas"]["UpdateDownloadClient"]
export type DownloadClientSettings = components["schemas"]["DownloadClientSettings"]
export type GrabRelease = components["schemas"]["GrabRelease"]
export type QBittorrentSettings = components["schemas"]["QBittorrentSettings"]
export type TransmissionSettings = components["schemas"]["TransmissionSettings"]
export type DelugeSettings = components["schemas"]["DelugeSettings"]
export type RTorrentSettings = components["schemas"]["RTorrentSettings"]
export type SyncProfile = components["schemas"]["SyncProfile"]
export type CreateSyncProfile = components["schemas"]["CreateSyncProfile"]
export type UpdateSyncProfile = components["schemas"]["UpdateSyncProfile"]
export type CrossSeedSnippet = components["schemas"]["CrossSeedSnippet"]
export type ConnectionIndexer = components["schemas"]["ConnectionIndexer"]
export type ConnectionStatus = components["schemas"]["ConnectionStatus"]
export type SyncResult = components["schemas"]["SyncResult"]
export type SyncReport = components["schemas"]["SyncReport"]
export type ConnectionSyncResult = components["schemas"]["ConnectionSyncResult"]
export type ApiKey = components["schemas"]["ApiKey"]
export type MintedApiKey = components["schemas"]["MintedApiKey"]
export type IndexerStats = components["schemas"]["IndexerStats"]
export type IndexerFailureCounts = components["schemas"]["IndexerStats"]["failures"]
export type IndexerBudget = components["schemas"]["IndexerBudget"]
export type IndexerBudgetKind = components["schemas"]["IndexerBudgetKind"]
export type CacheStats = components["schemas"]["CacheStats"]
export type CacheIndexerStats = components["schemas"]["CacheIndexerStats"]
export type DiagnosticCapture = components["schemas"]["DiagnosticCapture"]
export type CacheConfig = components["schemas"]["CacheConfig"]
export type CacheConfigUpdate = components["schemas"]["CacheConfigUpdate"]
export type ConnectionKind = components["schemas"]["AppConnection"]["kind"]
export type AnnounceKind = components["schemas"]["AnnounceConnection"]["kind"]
export type ProxyType = components["schemas"]["Proxy"]["type"]
export type DownloadClientKind = components["schemas"]["DownloadClient"]["kind"]
// LogLevel is the bare string union call sites switch on; components["schemas"]["LogLevel"]
// is the {level: LogLevel} wrapper the get/set endpoints exchange.
export type LogLevel = components["schemas"]["LogLevel"]["level"]

// FrontendLogLevel is the smaller enum POST /api/logs/frontend accepts (lib/notify.ts's
// shipping set — no "trace"/"debug"). Pulled from the operation's inline request schema
// since it has no named components["schemas"] entry.
export type FrontendLogLevel =
  operations["postFrontendLog"]["requestBody"]["content"]["application/json"]["level"]

// Response shapes with no named schema component: the spec declares them inline, so
// they're pulled from the operation's response instead of a components["schemas"] key.
export type Me = operations["me"]["responses"]["200"]["content"]["application/json"]
export type SetupState = operations["getSetupStatus"]["responses"]["200"]["content"]["application/json"]
export type Health = operations["getHealthz"]["responses"]["200"]["content"]["application/json"]
export type IndexerStatus = operations["indexerStatus"]["responses"]["200"]["content"]["application/json"]
export type IndexerDiagnostics = operations["indexerDiagnostics"]["responses"]["200"]["content"]["application/json"]
export type SearchParams = NonNullable<operations["searchIndexer"]["parameters"]["query"]>

export type Credentials = components["schemas"]["Credentials"]
export type OIDCConfig = components["schemas"]["OIDCConfig"]

// The keep-stored sentinel for secret settings (see openapi.yaml Setting) — a value,
// not a spec-mirrored type, so it stays hand-written.
export const REDACTED = "<redacted>"

// APIError carries the server's error envelope ({error, code}) plus the HTTP
// status, so callers branch on `code` (e.g. "invalid_credentials"), never on
// message text.
export class APIError extends Error {
  readonly status: number
  readonly code: string

  constructor(status: number, code: string, message: string) {
    super(message)
    this.name = "APIError"
    this.status = status
    this.code = code
  }
}

const MUTATING = new Set(["POST", "PUT", "PATCH", "DELETE"])

// AUTH_BOOTSTRAP endpoints handle their own 401 inline (session probe, login,
// setup, logout), so they are exempt from the 401 hard-redirect that every other
// endpoint triggers. A protected action (e.g. change-password) is NOT here — its
// 401 means the session expired and should redirect.
const AUTH_BOOTSTRAP = new Set(["/api/auth/me", "/api/auth/login", "/api/auth/setup", "/api/auth/logout"])

// readCsrfCookie returns the non-HttpOnly CSRF companion cookie the server
// sets at login (internal/web/api/csrf.go), or "" when absent.
function readCsrfCookie(): string {
  const match = document.cookie.match(/(?:^|;\s*)harbrr_csrf=([^;]*)/)
  return match ? decodeURIComponent(match[1]) : ""
}

type ErrorBody = { error?: string, code?: string }

// filenameFromContentDisposition pulls filename="..." out of an attachment
// Content-Disposition header, falling back to a dated default when the header
// is absent or unparseable.
function filenameFromContentDisposition(header: string | null): string {
  const match = header?.match(/filename="?([^"; ]+)"?/)
  return match?.[1] ?? `harbrr-backup-${new Date().toISOString().slice(0, 10)}.json`
}

// setParams drops undefined/empty-string values so an unset search field is omitted
// from the querystring entirely rather than sent as an empty filter.
function setParams(params: SearchParams): SearchParams {
  const query: SearchParams = {}
  for (const [key, value] of Object.entries(params) as [keyof SearchParams, unknown][]) {
    if (value !== undefined && value !== "") (query as Record<string, unknown>)[key] = value
  }
  return query
}

// onAuthScreen reports whether the user is already on the login/setup screen,
// where a 401 hard-redirect would loop or be meaningless (bootstrap probes,
// failed logins).
function onAuthScreen(): boolean {
  return ["/login", "/setup"].includes(window.location.pathname.replace(getBaseUrl(), ""))
}

// toAPIError builds the thrown error for a non-ok response. Shared by unwrap and
// exportBackup (which needs the raw Response for its headers, not a JSON-unwrapped
// value). The 401 hard-redirect is the onResponse middleware's job, not this one's.
function toAPIError(response: Response, error: unknown): APIError {
  const body = (typeof error === "object" && error !== null ? error : undefined) as ErrorBody | undefined
  let code = "internal"
  let message = response.statusText
  if (body?.code) code = body.code
  if (body?.error) message = body.error
  return new APIError(response.status, code, message)
}

// unwrap turns an openapi-fetch {data, error, response} result into the resolved
// value or a thrown APIError. T is INFERRED from the typed client call's data
// shape — never pass it explicitly — so each method's declared return type is
// checked against what the generated types say the endpoint actually returns.
async function unwrap<T>(call: Promise<{ data?: T, error?: unknown, response: Response }>): Promise<T> {
  const { data, error, response } = await call
  if (!response.ok) throw toAPIError(response, error)
  return data as T
}

// ApiClient is the single choke point every management call goes through:
// base-path prefixing, CSRF header injection on mutations (onRequest middleware),
// the {error, code} envelope parsed into APIError, and the 401 hard-redirect to
// /login (onResponse middleware — skipped for auth endpoints and on the
// login/setup screens, so bootstrap probes and failed logins cannot loop).
// NEVER log request or response payloads here — settings bodies carry tracker
// credentials.
export class ApiClient {
  private csrfToken = ""
  private readonly http: Client<paths>

  // fetchFn is the transport behind every request and the injection seam tests use
  // (see src/test/stubApi.ts): a stub here still runs the whole middleware pipeline,
  // so CSRF injection and the 401 redirect behave exactly as in production. It is a
  // replaceable field rather than a constructor-only capture because component tests
  // reach the module singleton through the hooks — stubApi swaps the singleton's
  // transport for the duration of a test and restores it after.
  fetchFn: (input: Request) => Promise<Response>

  // baseUrl is made absolute (origin + path prefix) because openapi-fetch constructs
  // a `Request` itself before dispatching — a plain browser `fetch("/api/...")` (the
  // old hand-rolled client's approach) resolves a relative URL against the document
  // implicitly, but `new Request("/api/...")` does not, so the origin is spelled out.
  // This is the same absolute URL the browser would have resolved either way.
  constructor(fetchFn?: (input: Request) => Promise<Response>) {
    this.fetchFn = fetchFn ?? ((input) => globalThis.fetch(input))
    this.http = createClient<paths>({
      baseUrl: `${window.location.origin}${getBaseUrl()}`,
      credentials: "same-origin",
      fetch: (input: Request) => this.fetchFn(input),
    })
    this.http.use({
      onRequest: ({ request }) => {
        if (MUTATING.has(request.method)) {
          const token = this.csrf()
          if (token !== "") request.headers.set("X-CSRF-Token", token)
        }
      },
      // schemaPath is the OpenAPI path including curly braces — the same spelling
      // as AUTH_BOOTSTRAP's entries.
      onResponse: ({ schemaPath, response }) => {
        if (response.status !== 401) return
        if (AUTH_BOOTSTRAP.has(schemaPath)) return
        if (onAuthScreen()) return
        this.onUnauthorized()
      },
    })
  }

  // onUnauthorized is replaceable for tests; the default is a full-page
  // navigation so all client state resets. It appends the current in-app location
  // as ?redirect= so an expired-session bounce returns the user where they were —
  // skipped on the auth screens themselves (which would loop / be meaningless).
  onUnauthorized: () => void = () => {
    const base = getBaseUrl()
    const target = `${base}/login`
    const path = window.location.pathname.slice(base.length) || "/"
    if (path === "/login" || path === "/setup") {
      window.location.assign(target)
      return
    }
    const redirect = path + window.location.search
    window.location.assign(`${target}?redirect=${encodeURIComponent(redirect)}`)
  }

  setCsrfToken(token: string | undefined) {
    this.csrfToken = token ?? ""
  }

  private csrf(): string {
    return readCsrfCookie() || this.csrfToken
  }

  // --- auth ---

  async getMe(): Promise<Me> {
    const me = await unwrap(this.http.GET("/api/auth/me"))
    this.setCsrfToken(me.csrfToken)
    return me
  }

  getSetup(): Promise<SetupState> {
    return unwrap(this.http.GET("/api/auth/setup"))
  }

  setup(creds: Credentials): Promise<operations["postSetup"]["responses"]["201"]["content"]["application/json"]> {
    return unwrap(this.http.POST("/api/auth/setup", { body: creds }))
  }

  login(creds: Credentials): Promise<void> {
    return unwrap(this.http.POST("/api/auth/login", { body: creds }))
  }

  logout(): Promise<void> {
    return unwrap(this.http.POST("/api/auth/logout"))
  }

  changePassword(currentPassword: string, newPassword: string): Promise<void> {
    return unwrap(this.http.POST("/api/auth/change-password", { body: { currentPassword, newPassword } }))
  }

  // getOIDCConfig probes the login screen's OIDC/SSO posture. The endpoint itself
  // always answers 200 (disabled default) even when OIDC isn't configured — the
  // catch here is a defensive fallback for the request failing outright (network,
  // server down), so the login screen still renders the password form.
  async getOIDCConfig(): Promise<OIDCConfig> {
    try {
      return await unwrap(this.http.GET("/api/auth/oidc/config"))
    } catch {
      return { enabled: false, authorizationUrl: "", disableBuiltInLogin: false, issuerUrl: "" }
    }
  }

  // --- definitions ---

  listDefinitions(): Promise<DefinitionEntry[]> {
    return unwrap(this.http.GET("/api/definitions"))
  }

  getDefinition(id: string): Promise<DefinitionDetail> {
    return unwrap(this.http.GET("/api/definitions/{id}", { params: { path: { id } } }))
  }

  // --- indexers ---

  listIndexers(): Promise<Instance[]> {
    return unwrap(this.http.GET("/api/indexers"))
  }

  addIndexer(body: AddIndexer): Promise<Instance> {
    return unwrap(this.http.POST("/api/indexers", { body }))
  }

  getIndexer(slug: string): Promise<InstanceDetail> {
    return unwrap(this.http.GET("/api/indexers/{slug}", { params: { path: { slug } } }))
  }

  // The server answers 204 (no body) on update, not the updated Instance — the old
  // hand-written type claimed `Promise<Instance>`, but no caller ever read the
  // resolved value (useUpdateIndexer invalidates and refetches instead), so this
  // return type is a pure accuracy fix, not a behavior change.
  updateIndexer(slug: string, body: UpdateIndexer): Promise<void> {
    return unwrap(this.http.PATCH("/api/indexers/{slug}", { params: { path: { slug } }, body }))
  }

  deleteIndexer(slug: string): Promise<void> {
    return unwrap(this.http.DELETE("/api/indexers/{slug}", { params: { path: { slug } } }))
  }

  setIndexerEnabled(slug: string, enabled: boolean): Promise<void> {
    if (enabled) return unwrap(this.http.POST("/api/indexers/{slug}/enable", { params: { path: { slug } } }))
    return unwrap(this.http.POST("/api/indexers/{slug}/disable", { params: { path: { slug } } }))
  }

  testIndexer(slug: string): Promise<TestResult> {
    return unwrap(this.http.POST("/api/indexers/{slug}/test", { params: { path: { slug } } }))
  }

  getIndexerStatus(slug: string): Promise<IndexerStatus> {
    return unwrap(this.http.GET("/api/indexers/{slug}/status", { params: { path: { slug } } }))
  }

  getIndexerDiagnostics(slug: string): Promise<IndexerDiagnostics> {
    return unwrap(this.http.GET("/api/indexers/{slug}/diagnostics", { params: { path: { slug } } }))
  }

  getIndexerStats(slug: string): Promise<IndexerStats> {
    return unwrap(this.http.GET("/api/indexers/{slug}/stats", { params: { path: { slug } } }))
  }

  getIndexerCapabilities(slug: string): Promise<Capabilities> {
    return unwrap(this.http.GET("/api/indexers/{slug}/capabilities", { params: { path: { slug } } }))
  }

  getCrossseedSnippet(slug: string): Promise<CrossSeedSnippet> {
    return unwrap(this.http.GET("/api/indexers/{slug}/crossseed-snippet", { params: { path: { slug } } }))
  }

  // --- backup export/import ---

  // exportBackup returns the encrypted bundle as a downloadable Blob rather than
  // going through unwrap: the response is offered as a file (Content-Disposition:
  // attachment), so the caller needs the raw bytes/filename, not a JSON-unwrapped
  // value. The bundle itself is still JSON (the {schemaVersion, payload} envelope),
  // so the parsed `data` is re-serialized into the Blob.
  async exportBackup(passphrase: string): Promise<{ blob: Blob, filename: string }> {
    const { data, error, response } = await this.http.POST("/api/export", { body: { passphrase } })
    if (!response.ok) throw toAPIError(response, error)
    const filename = filenameFromContentDisposition(response.headers.get("Content-Disposition"))
    return { blob: new Blob([JSON.stringify(data)], { type: "application/json" }), filename }
  }

  // importBackup restores a bundle (wipe-and-load). 409 (non-empty instance, no
  // force) and 400 (wrong passphrase / malformed payload) surface as APIError with
  // the matching `.status` for the caller to branch on.
  importBackup(payload: string, passphrase: string, force?: boolean): Promise<void> {
    return unwrap(this.http.POST("/api/import", { body: { payload, passphrase, force } }))
  }

  // --- settings surfaces ---

  getHealth(): Promise<Health> {
    // /healthz lives beside /api, not under it.
    return unwrap(this.http.GET("/healthz"))
  }

  // getServerInfo reflects the live config.ServerConfig.Port, used to detect
  // app-sync connections whose stored harbrrUrl port has gone stale.
  getServerInfo(): Promise<components["schemas"]["ServerInfo"]> {
    return unwrap(this.http.GET("/api/server-info"))
  }

  listApiKeys(): Promise<ApiKey[]> {
    return unwrap(this.http.GET("/api/apikeys"))
  }

  mintApiKey(name: string): Promise<MintedApiKey> {
    return unwrap(this.http.POST("/api/apikeys", { body: { name } }))
  }

  revokeApiKey(id: number): Promise<void> {
    return unwrap(this.http.DELETE("/api/apikeys/{id}", { params: { path: { id } } }))
  }

  listNotifications(): Promise<Notification[]> {
    return unwrap(this.http.GET("/api/notifications"))
  }

  createNotification(body: CreateNotification): Promise<Notification> {
    return unwrap(this.http.POST("/api/notifications", { body }))
  }

  // The server answers 204 on update; see the updateIndexer note (no caller reads
  // the resolved value — useUpdateNotification invalidates and refetches instead).
  updateNotification(id: number, body: UpdateNotification): Promise<void> {
    return unwrap(this.http.PATCH("/api/notifications/{id}", { params: { path: { id } }, body }))
  }

  deleteNotification(id: number): Promise<void> {
    return unwrap(this.http.DELETE("/api/notifications/{id}", { params: { path: { id } } }))
  }

  setNotificationEnabled(id: number, enabled: boolean): Promise<void> {
    if (enabled) return unwrap(this.http.POST("/api/notifications/{id}/enable", { params: { path: { id } } }))
    return unwrap(this.http.POST("/api/notifications/{id}/disable", { params: { path: { id } } }))
  }

  testNotification(id: number): Promise<TestResult> {
    return unwrap(this.http.POST("/api/notifications/{id}/test", { params: { path: { id } } }))
  }

  // --- proxies ---

  listProxies(): Promise<Proxy[]> {
    return unwrap(this.http.GET("/api/proxies"))
  }

  createProxy(body: CreateProxy): Promise<Proxy> {
    return unwrap(this.http.POST("/api/proxies", { body }))
  }

  updateProxy(id: number, body: UpdateProxy): Promise<void> {
    return unwrap(this.http.PATCH("/api/proxies/{id}", { params: { path: { id } }, body }))
  }

  deleteProxy(id: number): Promise<void> {
    return unwrap(this.http.DELETE("/api/proxies/{id}", { params: { path: { id } } }))
  }

  // --- solvers ---

  listSolvers(): Promise<Solver[]> {
    return unwrap(this.http.GET("/api/solvers"))
  }

  createSolver(body: CreateSolver): Promise<Solver> {
    return unwrap(this.http.POST("/api/solvers", { body }))
  }

  updateSolver(id: number, body: UpdateSolver): Promise<void> {
    return unwrap(this.http.PATCH("/api/solvers/{id}", { params: { path: { id } }, body }))
  }

  deleteSolver(id: number): Promise<void> {
    return unwrap(this.http.DELETE("/api/solvers/{id}", { params: { path: { id } } }))
  }

  // --- download clients ---

  listDownloadClients(): Promise<DownloadClient[]> {
    return unwrap(this.http.GET("/api/download-clients"))
  }

  createDownloadClient(body: CreateDownloadClient): Promise<DownloadClient> {
    return unwrap(this.http.POST("/api/download-clients", { body }))
  }

  updateDownloadClient(id: number, body: UpdateDownloadClient): Promise<void> {
    return unwrap(this.http.PATCH("/api/download-clients/{id}", { params: { path: { id } }, body }))
  }

  deleteDownloadClient(id: number): Promise<void> {
    return unwrap(this.http.DELETE("/api/download-clients/{id}", { params: { path: { id } } }))
  }

  setDownloadClientEnabled(id: number, enabled: boolean): Promise<void> {
    if (enabled) return unwrap(this.http.POST("/api/download-clients/{id}/enable", { params: { path: { id } } }))
    return unwrap(this.http.POST("/api/download-clients/{id}/disable", { params: { path: { id } } }))
  }

  grabToDownloadClient(id: number, body: GrabRelease): Promise<void> {
    return unwrap(this.http.POST("/api/download-clients/{id}/grab", { params: { path: { id } }, body }))
  }

  testDownloadClient(id: number): Promise<TestResult> {
    return unwrap(this.http.POST("/api/download-clients/{id}/test", { params: { path: { id } } }))
  }

  getCacheStats(): Promise<CacheStats> {
    return unwrap(this.http.GET("/api/cache/stats"))
  }

  flushCache(): Promise<components["schemas"]["CacheFlushResult"]> {
    return unwrap(this.http.POST("/api/cache/flush"))
  }

  resetCacheStats(): Promise<components["schemas"]["CacheStatsResetResult"]> {
    return unwrap(this.http.POST("/api/cache/stats/reset"))
  }

  getCacheConfig(): Promise<CacheConfig> {
    return unwrap(this.http.GET("/api/cache/config"))
  }

  updateCacheConfig(body: CacheConfigUpdate): Promise<CacheConfig> {
    return unwrap(this.http.PUT("/api/cache/config", { body }))
  }

  getLogLevel(): Promise<components["schemas"]["LogLevel"]> {
    return unwrap(this.http.GET("/api/config/log-level"))
  }

  setLogLevel(level: LogLevel): Promise<components["schemas"]["LogLevel"]> {
    return unwrap(this.http.PUT("/api/config/log-level", { body: { level } }))
  }

  getAdultCategories(): Promise<components["schemas"]["AdultCategories"]> {
    return unwrap(this.http.GET("/api/config/adult-categories"))
  }

  setAdultCategories(hidden: boolean): Promise<components["schemas"]["AdultCategories"]> {
    return unwrap(this.http.PUT("/api/config/adult-categories", { body: { hidden } }))
  }

  getExpiryThresholds(): Promise<components["schemas"]["ExpiryThresholds"]> {
    return unwrap(this.http.GET("/api/config/expiry-thresholds"))
  }

  setExpiryThresholds(days: number[]): Promise<components["schemas"]["ExpiryThresholds"]> {
    return unwrap(this.http.PUT("/api/config/expiry-thresholds", { body: { days } }))
  }

  // postFrontendLog relays a toast into the daemon's own log (see lib/notify.ts, the
  // only caller — never call this directly from a component).
  postFrontendLog(level: FrontendLogLevel, message: string, context?: string): Promise<void> {
    return unwrap(this.http.POST("/api/logs/frontend", { body: { level, message, context } }))
  }

  listAllIndexerStats(): Promise<IndexerStats[]> {
    return unwrap(this.http.GET("/api/indexers/stats"))
  }

  // --- app connections (sync targets) ---

  listConnections(): Promise<AppConnection[]> {
    return unwrap(this.http.GET("/api/app-connections"))
  }

  createConnection(body: CreateConnection): Promise<AppConnection> {
    return unwrap(this.http.POST("/api/app-connections", { body }))
  }

  getConnection(id: number): Promise<AppConnection> {
    return unwrap(this.http.GET("/api/app-connections/{id}", { params: { path: { id } } }))
  }

  // The server answers 204 on update; see the updateIndexer note (no caller reads
  // the resolved value — useUpdateConnection invalidates and refetches instead).
  updateConnection(id: number, body: UpdateConnection): Promise<void> {
    return unwrap(this.http.PATCH("/api/app-connections/{id}", { params: { path: { id } }, body }))
  }

  deleteConnection(id: number): Promise<void> {
    return unwrap(this.http.DELETE("/api/app-connections/{id}", { params: { path: { id } } }))
  }

  setConnectionEnabled(id: number, enabled: boolean): Promise<void> {
    if (enabled) return unwrap(this.http.POST("/api/app-connections/{id}/enable", { params: { path: { id } } }))
    return unwrap(this.http.POST("/api/app-connections/{id}/disable", { params: { path: { id } } }))
  }

  testConnection(id: number): Promise<TestResult> {
    return unwrap(this.http.POST("/api/app-connections/{id}/test", { params: { path: { id } } }))
  }

  syncConnection(id: number): Promise<SyncReport> {
    return unwrap(this.http.POST("/api/app-connections/{id}/sync", { params: { path: { id } } }))
  }

  syncAllConnections(): Promise<ConnectionSyncResult[]> {
    return unwrap(this.http.POST("/api/app-connections/sync"))
  }

  getConnectionStatus(id: number): Promise<ConnectionStatus> {
    return unwrap(this.http.GET("/api/app-connections/{id}/status", { params: { path: { id } } }))
  }

  // --- apps (first-class (kind, base_url) identities, ADR 0004) ---

  listApps(): Promise<App[]> {
    return unwrap(this.http.GET("/api/apps"))
  }

  getApp(id: number): Promise<App> {
    return unwrap(this.http.GET("/api/apps/{id}", { params: { path: { id } } }))
  }

  // The server answers 204 on update; see the updateIndexer note (no caller reads
  // the resolved value — useUpdateApp invalidates and refetches instead).
  updateApp(id: number, body: UpdateApp): Promise<void> {
    return unwrap(this.http.PATCH("/api/apps/{id}", { params: { path: { id } }, body }))
  }

  deleteApp(id: number): Promise<void> {
    return unwrap(this.http.DELETE("/api/apps/{id}", { params: { path: { id } } }))
  }

  getQuiInstances(id: number): Promise<QuiInstances> {
    return unwrap(this.http.GET("/api/apps/{id}/qui-instances", { params: { path: { id } } }))
  }

  // --- sync profiles (indexer routing sets) ---

  listSyncProfiles(): Promise<SyncProfile[]> {
    return unwrap(this.http.GET("/api/sync-profiles"))
  }

  createSyncProfile(body: CreateSyncProfile): Promise<SyncProfile> {
    return unwrap(this.http.POST("/api/sync-profiles", { body }))
  }

  // The server answers 204 on update; see the updateIndexer note (no caller reads
  // the resolved value — useUpdateSyncProfile invalidates and refetches instead).
  updateSyncProfile(id: number, body: UpdateSyncProfile): Promise<void> {
    return unwrap(this.http.PATCH("/api/sync-profiles/{id}", { params: { path: { id } }, body }))
  }

  deleteSyncProfile(id: number): Promise<void> {
    return unwrap(this.http.DELETE("/api/sync-profiles/{id}", { params: { path: { id } } }))
  }

  // --- announce connections (cross-seed push targets) ---

  listAnnounceConnections(): Promise<AnnounceConnection[]> {
    return unwrap(this.http.GET("/api/announce-connections"))
  }

  createAnnounceConnection(body: CreateAnnounceConnection): Promise<AnnounceConnection> {
    return unwrap(this.http.POST("/api/announce-connections", { body }))
  }

  // The server answers 204 on update; see the updateIndexer note (no caller reads
  // the resolved value — useUpdateAnnounce invalidates and refetches instead).
  updateAnnounceConnection(id: number, body: UpdateAnnounceConnection): Promise<void> {
    return unwrap(this.http.PATCH("/api/announce-connections/{id}", { params: { path: { id } }, body }))
  }

  deleteAnnounceConnection(id: number): Promise<void> {
    return unwrap(this.http.DELETE("/api/announce-connections/{id}", { params: { path: { id } } }))
  }

  setAnnounceEnabled(id: number, enabled: boolean): Promise<void> {
    if (enabled) return unwrap(this.http.POST("/api/announce-connections/{id}/enable", { params: { path: { id } } }))
    return unwrap(this.http.POST("/api/announce-connections/{id}/disable", { params: { path: { id } } }))
  }

  testAnnounceConnection(id: number): Promise<TestResult> {
    return unwrap(this.http.POST("/api/announce-connections/{id}/test", { params: { path: { id } } }))
  }

  // --- search ---

  searchIndexer(slug: string, params: SearchParams): Promise<SearchResults> {
    return unwrap(this.http.GET("/api/indexers/{slug}/search", { params: { path: { slug }, query: setParams(params) } }))
  }

  // One search across a subset, merged and sorted by the server (autobrr/harbrr#372):
  // one request, one window, one ledger — no client-side fan-out.
  searchAggregate(slugs: string[], params: SearchParams): Promise<AggregateSearchResults> {
    return unwrap(this.http.GET("/api/search", { params: { query: { ...setParams(params), indexers: slugs.join(",") } } }))
  }
}

// createApi builds a fresh client — its own middleware stack and onUnauthorized —
// so tests do not leak into each other. Pass a fetch to inject a transport
// (src/test/stubApi.ts); omit it for the real network.
export function createApi(fetchFn?: (input: Request) => Promise<Response>): ApiClient {
  return new ApiClient(fetchFn)
}

export const api = createApi()
