package main

import (
	"bufio"
	"fmt"
	"os"
	"strconv"
	"strings"
)

// smokeEnvKeys is the ordered set of SMOKE_* variables the smoke command reads and
// writes, so a generated smoke.env is deterministic and groups each app's URL+key.
var smokeEnvKeys = []string{
	"SMOKE_HARBRR_URL", "SMOKE_HARBRR_APIKEY",
	"SMOKE_PROWLARR_URL", "SMOKE_PROWLARR_APIKEY",
	"SMOKE_SONARR_URL", "SMOKE_SONARR_APIKEY",
	"SMOKE_RADARR_URL", "SMOKE_RADARR_APIKEY",
	"SMOKE_QUI_URL", "SMOKE_QUI_APIKEY",
}

// parseEnvFile reads a `smoke.env` style file into a map. Each non-blank, non-comment
// line is `[export ]KEY=VALUE`; a quoted VALUE is unquoted (Go-string first, then a
// plain surrounding-quote trim), so it round-trips with writeEnvFile. A missing file is
// not an error (returns an empty map) — the process env may supply everything.
func parseEnvFile(path string) (map[string]string, error) {
	out := map[string]string{}
	f, err := os.Open(path)
	if err != nil {
		if os.IsNotExist(err) {
			return out, nil
		}
		return nil, fmt.Errorf("smoke: open env file: %w", err)
	}
	defer f.Close()

	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		line = strings.TrimPrefix(line, "export ")
		k, v, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		out[strings.TrimSpace(k)] = unquoteEnv(strings.TrimSpace(v))
	}
	if err := sc.Err(); err != nil {
		return nil, fmt.Errorf("smoke: read env file: %w", err)
	}
	return out, nil
}

// unquoteEnv reverses writeEnvFile's quoting: it prefers Go-string unquoting, falling
// back to trimming a single pair of surrounding quotes for a hand-edited value.
func unquoteEnv(v string) string {
	if s, err := strconv.Unquote(v); err == nil {
		return s
	}
	if len(v) >= 2 && (v[0] == '"' || v[0] == '\'') && v[len(v)-1] == v[0] {
		return v[1 : len(v)-1]
	}
	return v
}

// writeEnvFile writes the known SMOKE_* keys present in kv (in smokeEnvKeys order) as
// `export KEY="value"` lines at mode 0600. Values are Go-quoted so they round-trip and
// never break on a space or quote.
func writeEnvFile(path string, kv map[string]string) error {
	var b strings.Builder
	b.WriteString("# harbrr smoke config — generated by `harbrr smoke`. Keys are secret; do not commit.\n")
	for _, k := range smokeEnvKeys {
		v, ok := kv[k]
		if !ok {
			continue
		}
		fmt.Fprintf(&b, "export %s=%s\n", k, strconv.Quote(v))
	}
	if err := os.WriteFile(path, []byte(b.String()), 0o600); err != nil {
		return fmt.Errorf("smoke: write env file: %w", err)
	}
	return nil
}
