package main

import (
	"bufio"
	"fmt"
	"maps"
	"os"
	"slices"
	"strconv"
	"strings"
)

// smokeEnvKeys is the ordered set of app URL/key SMOKE_* variables the reconfigure flow
// prompts for and rewrites, so a generated smoke.env is deterministic and groups each
// app's URL+key. It is DERIVED from smokePrompts so the prompt order and the file order
// can never drift. It intentionally excludes hand-added keys (SMOKE_QUERY etc.): those
// are not prompted, so they must be preserved verbatim rather than treated as
// reconfigurable.
var smokeEnvKeys = func() []string {
	keys := make([]string, 0, 2*len(smokePrompts))
	for _, p := range smokePrompts {
		keys = append(keys, p.urlKey, p.keyKey)
	}
	return keys
}()

// isSmokeAppEnvKey reports whether k is one of the recognized app URL/key variables that
// the reconfigure flow re-prompts for (and so may drop when an app is cleared/skipped).
// Any other SMOKE_* key is hand-added and must survive a reconfigure untouched.
func isSmokeAppEnvKey(k string) bool {
	return slices.Contains(smokeEnvKeys, k)
}

// parseEnvFile reads a `smoke.env` style file into a map. Each non-blank, non-comment
// line is `[export ]KEY=VALUE`; a quoted VALUE is unquoted (Go-string first, then a
// plain surrounding-quote trim), so it round-trips with writeEnvFile. A missing file is
// not an error (returns an empty map) — the process env may supply everything.
func parseEnvFile(path string) (map[string]string, error) {
	out := map[string]string{}
	f, err := os.Open(path)
	if err != nil {
		if os.IsNotExist(err) {
			return out, nil
		}
		return nil, fmt.Errorf("smoke: open env file: %w", err)
	}
	defer f.Close()

	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		line = strings.TrimPrefix(line, "export ")
		k, v, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		out[strings.TrimSpace(k)] = unquoteEnv(strings.TrimSpace(v))
	}
	if err := sc.Err(); err != nil {
		return nil, fmt.Errorf("smoke: read env file: %w", err)
	}
	return out, nil
}

// unquoteEnv reverses writeEnvFile's quoting: it prefers Go-string unquoting, falling
// back to trimming a single pair of surrounding quotes for a hand-edited value.
func unquoteEnv(v string) string {
	if s, err := strconv.Unquote(v); err == nil {
		return s
	}
	if len(v) >= 2 && (v[0] == '"' || v[0] == '\'') && v[len(v)-1] == v[0] {
		return v[1 : len(v)-1]
	}
	return v
}

// writeEnvFile writes every key in kv as an `export KEY="value"` line at mode 0600: the
// known app keys first in smokeEnvKeys order (grouping each app's URL+key), then any
// remaining hand-added keys (e.g. SMOKE_QUERY) in sorted order. Nothing in kv is dropped,
// so a reconfigure preserves manually-added lines. Values are Go-quoted so they round-trip
// and never break on a space or quote.
func writeEnvFile(path string, kv map[string]string) error {
	var b strings.Builder
	b.WriteString("# harbrr smoke config — generated by `harbrr smoke`. Keys are secret; do not commit.\n")
	for _, k := range smokeEnvKeys {
		if v, ok := kv[k]; ok {
			fmt.Fprintf(&b, "export %s=%s\n", k, strconv.Quote(v))
		}
	}
	for _, k := range slices.Sorted(maps.Keys(kv)) {
		if !isSmokeAppEnvKey(k) {
			fmt.Fprintf(&b, "export %s=%s\n", k, strconv.Quote(kv[k]))
		}
	}
	if err := os.WriteFile(path, []byte(b.String()), 0o600); err != nil {
		return fmt.Errorf("smoke: write env file: %w", err)
	}
	return nil
}
